name: ci
on:
    push:
      branches:
        - 'master'
jobs:
    ci-cd:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Staring Node.js
              uses: actions/setup-node@v3
            - name: Set npmrc and install dependencies
              run: npm i
            - name: Run tests
              run: npm run test
            - name: Stop workflow on test failure
              if: failure()
              run: exit 1
            - name: Deploy
              run: echo Deployed