name: ci
on:
    push:
      branches:
        - 'master'
jobs:
    ci-cd:
        runs-on: windows-latest
        steps:
            - name: Staring Node.js
              uses: actions/setup-node@v3
            - name: Set npmrc and install dependencies
              run: yarn install
            - name: Run tests
              run: |
                ls
                yarn run build
            - name: Deploy
              run: echo Deployed